apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app
        image: 850133624498.dkr.ecr.us-east-1.amazonaws.com/clo835-app:latest
        env:
        - name: DBHOST
          value: "mysql-service.mysql.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue" # Change this to "pink" for Step 6 rolling update
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-secret